{
  "version": 1,
  "analyzers": [
      {
          "meta": {
              "import_path": "https://github.com/slytomcat/yandex-disk-simulator"
          },
          "name": "go",
          "enabled": true
      }
  ],
  "test_patterns": [
      "**/*_test.go"
  ]
}